services:

  postgres:
    container_name: merchants-postgres
    image: postgres:15
    environment:
      POSTGRES_USER: merchant
      POSTGRES_PASSWORD: 12345678
    ports: 
      - '5432:5432'
    volumes:
      - merchants-postgres:/var/lib/postgresql/data

  redis:
    container_name: merchants-redis
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - merchants-redis:/var/lib/redis/data

  merchants:
    container_name: merchants-api
    build:
      context: .
    volumes:
      - ./merchants-api:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history 

  sidekiq:
    container_name: merchants-sidekiq
    build:
      context: .
      #args:
      #  USER_ID: "${USER_ID:-1000}"
      #  GROUP_ID: "${GROUP_ID:-1000}"
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    env_file:
      - .env

volumes:
  merchants-postgres:
  merchants-redis: