services:

  postgres:
    container_name: merchants-postgres
    image: postgres:15
    environment:
      POSTGRES_USER: merchant
      POSTGRES_PASSWORD: 12345678
    ports: 
      - '5432:5432'
    volumes:
      - merchants-postgres:/var/lib/postgresql/data

  redis:
    container_name: merchants-redis
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - merchants-redis:/var/lib/redis/data

  merchants-api:
    container_name: merchants-api
    build:
      context: .
    volumes:
      - ./merchants-api:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '4000:4000'
    env_file:
      - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history 

  sidekiq:
    container_name: merchants-sidekiq
    build:
      context: .
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    env_file:
      - .env
  
  merchants-app:
    container_name: merchants-app
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - 3000:3000
    volumes:
      - ./merchants-app/src:/merchants-app/src
    depends_on:
      - merchants-api
    environment:
      - WATCHPACK_POLLING=true

volumes:
  merchants-postgres:
  merchants-redis: