---
openapi: 3.0.1
info:
  title: Merchants API
  version: v1
paths:
  "/admins":
    $ref: './admins/registration.yaml'
  "/auth":
    $ref: './admins/login.yaml'
  "/dashboard":
    $ref: './dashboard.yaml'
  "/merchants/auth":
    $ref: './merchants/login.yaml'
  "/payments":
    $ref: './payments/payment.yaml'
servers:
  - url: "{protocol}://{server}"
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      server:
        enum:
          - localhost:4000
        default: localhost:4000/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
